export const ROLES = {
  LEADER: 'LEADER',
  MEMBER: 'MEMBER',
  ADMIN: 'ADMIN',
};

export const PERMISSIONS = {
  CAN_EDIT_TEAM: [ROLES.LEADER, ROLES.ADMIN],
  CAN_SUBMIT_PAPER: [ROLES.LEADER, ROLES.ADMIN],
  CAN_INVITE: [ROLES.LEADER, ROLES.ADMIN],
};
